/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import base_datos.DetallePrestamoDao;
import base_datos.PrestamoDao;
import base_datos.SocioDao;
import clases.DetallePrestamo;
import clases.Libro;
import clases.Prestamo;
import clases.Socio;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEBASXD
 */
public class frmPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form frmPrestamo
     */
    public frmPrestamo() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        actualizarTabla();
    }
    
    public void actualizarTabla(){
        DefaultTableModel modeloTabla;
        modeloTabla = (DefaultTableModel)jtbPrestamo.getModel();
        Object[] obj_prestamo = new Object[4];
        
        PrestamoDao prestamodao = new PrestamoDao();
        
        ArrayList<DetallePrestamo> arr_prestamos = new ArrayList<DetallePrestamo>();
        arr_prestamos = prestamodao.actualizar_prestamo();
        
        //recorrer un array list
        Iterator<DetallePrestamo> iterator_prestamos = arr_prestamos.iterator();
        while(iterator_prestamos.hasNext()){
            DetallePrestamo objeto_prestamo = iterator_prestamos.next();
            obj_prestamo[0] = objeto_prestamo.getId_prestamo();
            obj_prestamo[1] = objeto_prestamo.getId_libro();
            obj_prestamo[2] = objeto_prestamo.getFecha_devolucion();
            obj_prestamo[3] = objeto_prestamo.getEstado();
            
            modeloTabla.addRow(obj_prestamo);
        }
        
        jtbPrestamo.setModel(modeloTabla);
    }
    
    
    
    private void limpiarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel)jtbPrestamo.getModel();
        int total_registros = jtbPrestamo.getRowCount() - 1;
        for(int i = total_registros; i >= 0; i--){
            modeloTabla.removeRow(i);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPrestamo = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Préstamo", "ID Libro", "Fecha Devolución", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPrestamoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbPrestamo);

        btnVolver.setBackground(new java.awt.Color(0, 102, 255));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnEntregar.setBackground(new java.awt.Color(255, 0, 102));
        btnEntregar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntregar.setText("Entregar Libro");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha entrega");

        jLabel3.setText("ID Préstamo");

        txtId.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtIdInputMethodTextChanged(evt);
            }
        });
        txtId.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtIdPropertyChange(evt);
            }
        });

        jLabel4.setText("Socio");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Préstamos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnEntregar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btnEntregar)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        frmSocio obj = new frmSocio();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jtbPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPrestamoMouseClicked
        // TODO add your handling code here:
        int index = jtbPrestamo.getSelectedRow();
        Object id = jtbPrestamo.getValueAt(index, 0);
        String strId = "" + id;
        txtId.setText(strId);
        
        int intId = Integer.parseInt(strId);
        Prestamo prestamo = new Prestamo(intId);
        PrestamoDao prestamodao = new PrestamoDao();
        Prestamo myPrestamo = prestamodao.consultar_socio(prestamo);
        txtNombre.setText(Integer.toString(myPrestamo.getId_prestamo()));
        
    }//GEN-LAST:event_jtbPrestamoMouseClicked

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        // TODO add your handling code here:
        
        String strFecha = txtFecha.getText();
        int index = jtbPrestamo.getSelectedRow();
        Object objFechaEstimada = jtbPrestamo.getValueAt(index, 2);
        String strFechaEstimada = "" + objFechaEstimada;
        
        PrestamoDao prestamodao = new PrestamoDao();
        SocioDao sociodao = new SocioDao();
        DetallePrestamoDao detalledao = new DetallePrestamoDao();
        
        try {
            Date dtFechaEstimada = new SimpleDateFormat("yyyy-MM-dd").parse(strFechaEstimada);
            Date dtFecha = new SimpleDateFormat("yyyy-MM-dd").parse(strFecha);
            if(dtFecha.after(dtFechaEstimada)){
                String strObj = txtNombre.getText();
                int intIdSocio = Integer.parseInt(strObj);
                Socio socio = new Socio(intIdSocio);
                sociodao.generar_multa(socio);
                JOptionPane.showMessageDialog(this, "Te pasaste de la fecha de entrega, se ha generado una multa", "Ups!! algo ha ido mal", JOptionPane.WARNING_MESSAGE);
                
            }            
            Object objIdPrestamo = jtbPrestamo.getValueAt(index, 0);
            String strIdPrestamo = objIdPrestamo.toString();
            int intId = Integer.parseInt(strIdPrestamo);
            DetallePrestamo prestamo = new DetallePrestamo(intId);
            detalledao.editar_prestamo(prestamo);
            
            Object objIdLibro = jtbPrestamo.getValueAt(index, 1);
            String strIdLibro = "" + objIdLibro;
            int intIdLibro = Integer.parseInt(strIdLibro);
            
            Libro libro = new Libro(intIdLibro);
            sociodao.devolver_libro(libro);            
            
            JOptionPane.showMessageDialog(this, "El libro ha sido devuelto y el prestamo ha sido eliminado con éxito!!", "Excelente", JOptionPane.INFORMATION_MESSAGE);
            limpiarTabla();
            actualizarTabla();
                
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Error al entregar el libro!", "Ups!! algo ha ido mal", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void txtIdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtIdInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdInputMethodTextChanged

    private void txtIdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtIdPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtbPrestamo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
